# user-service-argo-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: userservicealias=harbor.cloudpro.com.tr/helpdesk/user_service

    # 2. En yeni imajı al (Güncellendi)
    argocd-image-updater.argoproj.io/userservicealias.update-strategy: newest-build

    # 3. Güncellenecek Helm değeri
    argocd-image-updater.argoproj.io/userservicealias.helm.image-spec: image.tag

    # 4. Harbor kimlik bilgileri (Sondaki # kaldırıldı)
    argocd-image-updater.argoproj.io/userservicealias.pull-secret: secret:argocd/harbor-creds

    # 5. YENİ EKLENEN ANNOTATION: TLS doğrulamasını atla
    argocd-image-updater.argoproj.io/userservicealias.insecure-skip-verify: "true"

    # 6. Git'e yazma metodu
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    
    # 7. Commit atılacak branch
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default
  source:
    # ArgoCD'nin izleyeceği GitOps reponuzun adresi
    repoURL: 'https://dev.azure.com/umutcelik0234/HelpDesk_App/_git/helpdesk-gitops-manifests'
    # Bu repo içinde hangi Helm Chart klasörünü kullanacağı
    path: user-service-chart
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    # Uygulamanın deploy edileceği namespace
    namespace: helpdesk-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true