# user-service-argo-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: userservicealias=harbor.cloudpro.com.tr/helpdesk/user_service
    argocd-image-updater.argoproj.io/userservicealias.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/userservicealias.helm.image-tag: image.tag

spec:
  project: default
  source:
    # ArgoCD'nin izleyeceği GitOps reponuzun adresi
    repoURL: 'https://dev.azure.com/umutcelik0234/HelpDesk_App/_git/helpdesk-gitops-manifests'
    # Bu repo içinde hangi Helm Chart klasörünü kullanacağı
    path: user-service-chart
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    # Uygulamanın deploy edileceği namespace
    namespace: helpdesk-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true