helm:
  parameters:
  - name: image.repository
    value: harbor.cloudpro.com.tr/helpdesk/user_service
    forcestring: true
  - name: image.tag
    value: "140"
    forcestring: true
  - name: image.name
    value: harbor.cloudpro.com.tr/helpdesk/user_service
    forcestring: true
