replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/user_service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

config:
  databaseUrl: "postgresql://user_admin:Passw0rd12.@10.43.169.88:5432/user_db"
extraEnvVars:
  - name: VAULT_ADDR
    value: "https://vault.cloudpro.com.tr"
  - name: KEYCLOAK_ISSUER_URI
    value: "https://keycloak.cloudpro.com.tr/realms/helpdesk-realm"