replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/user_service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

config:
  databaseUrl: "postgresql://user_admin:Passw0rd12.@10.43.169.88:5432/user_db"
extraEnvVars:
  - name: VAULT_ADDR
    value: "https://10.77.3.203:443"
  - name: KEYCLOAK_ISSUER_URI
    value: "http://10.77.3.203/realms/helpdesk-realm"