replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/user_service
  pullPolicy: IfNotPresent
  # tag: "" alanı CI/CD tarafından güncellenir

service:
  type: ClusterIP
  port: 80

config:
  databaseUrl: "postgresql://user_admin:Passw0rd12.@10.43.169.88:5432/user_db"

# Bu bölümün TAM OLARAK bu şekilde olduğundan emin olun.
# Tüm Keycloak URL'leri HTTPS ve DNS adı ile belirtilmiştir.
extraEnvVars:
  - name: VAULT_ADDR
    value: "https://vault.cloudpro.com.tr"
    
  - name: KEYCLOAK_ISSUER_URI
    value: "https://keycloak.cloudpro.com.tr/realms/helpdesk-realm"
    
  - name: KEYCLOAK_JWKS_URI
    value: "https://keycloak.cloudpro.com.tr/realms/helpdesk-realm/protocol/openid-connect/certs"

  # Audience, frontend'den gelen token ile eşleşmeli.
  # Keycloak'ta 'helpdesk-frontend' client'ından gelen token'lar 'account' audience'ına sahip olabilir.
  # Eğer bu çalışmazsa 'helpdesk-frontend' olarak denenebilir, ama 'account' genellikle doğrudur.
  - name: KEYCLOAK_TOKEN_AUDIENCE
    value: "account"
    
  - name: KEYCLOAK_ADMIN_CLIENT_ID
    value: "user-service-admin-client" # veya sizin client adınız