# ticket-service-chart/values.yaml

replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/ticket_service
  pullPolicy: IfNotPresent
  tag: "117"

service:
  type: ClusterIP
  port: 80

# Pod'a doğrudan verilecek ortam değişkenleri
env:
  - name: DATABASE_URL
    value: "postgresql://ticket_admin:Passw0rd12.@10.43.43.21:5432/ticket_db"
  - name: VAULT_ADDR
    value: "https://vault.cloudpro.com.tr/"
  - name: KEYCLOAK_ISSUER_URI
    value: "https://keycloak.cloudpro.com.tr/realms/helpdesk-realm"
  - name: KEYCLOAK_JWKS_URI
    value: "https://keycloak.cloudpro.com.tr/realms/helpdesk-realm/protocol/openid-connect/certs"
  - name: KEYCLOAK_TOKEN_AUDIENCE
    value: "account"
  - name: KEYCLOAK_ADMIN_CLIENT_ID
    value: "ticket-service-admin-client"

# Kubernetes Secret'larından alınacak ortam değişkenleri
envFromSecret:
  - name: KEYCLOAK_ADMIN_CLIENT_SECRET
    secretName: ticket-service-secrets
    secretKey: KEYCLOAK_ADMIN_CLIENT_SECRET
  - name: VAULT_TOKEN
    secretName: vault-token-secret
    secretKey: VAULT_TOKEN
