# ticket-service-chart/values.yaml
# BU YAPI HEM TICKET HEM DE USER SERVISI IÇIN KULLANILACAKTIR.

replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/ticket_service # user-service için burayı güncelleyin
  pullPolicy: IfNotPresent
  tag: "117"

service:
  type: ClusterIP
  port: 80

# Pod'a doğrudan verilecek ortam değişkenleri
env:
  - name: DATABASE_URL
    value: "postgresql://ticket_admin:Passw0rd12.@10.43.43.21:5432/ticket_db" # Her servis için kendi DB adresini yazın
  - name: VAULT_ADDR
    value: "https://vault.cloudpro.com.tr/" # HTTPS olmadan ve portsuz deneyebiliriz: "http://10.77.3.203:8200"
  - name: KEYCLOAK_ISSUER_URI
    value: "http://10.77.3.203/realms/helpdesk-realm"
  - name: KEYCLOAK_JWKS_URI
    value: "http://10.77.3.203/realms/helpdesk-realm/protocol/openid-connect/certs"
  - name: KEYCLOAK_TOKEN_AUDIENCE
    value: "account"
  - name: KEYCLOAK_ADMIN_CLIENT_ID
    value: "ticket-service-admin-client" # user-service için kendi client ID'si

# Kubernetes Secret'larından alınacak ortam değişkenleri
envFromSecret:
  - name: KEYCLOAK_ADMIN_CLIENT_SECRET
    secretName: ticket-service-secrets # Her servis için kendi secret adı
    secretKey: KEYCLOAK_ADMIN_CLIENT_SECRET
  # --- YENİ EKLENEN BÖLÜM ---
  - name: VAULT_TOKEN
    secretName: vault-token-secret # Adım 1'de oluşturduğumuz secret'ın adı
    secretKey: VAULT_TOKEN
