# ticket-service-chart/values.yaml
replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/ticket_service # Depo adını güncelledik
  pullPolicy: IfNotPresent
  tag: "111" # Harbor'daki geçerli bir ticket_service etiketi

service:
  type: ClusterIP
  port: 80

config:
  # Veritabanı adını ve servis adını güncelledik
  databaseUrl: "postgresql://ticket_admin:Passw0rd12.@10.43.198.29:5432/ticket_db"