# ticket-service-chart/values.yaml
replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/ticket_service
  pullPolicy: IfNotPresent
  tag: "" #

service:
  type: ClusterIP
  port: 80

config:
  databaseUrl: "postgresql://ticket_admin:Passw0rd12.@10.43.43.21:5432/ticket_db"