# ingress/helpdesk-ingress.yaml (Düzeltilmiş Hali)

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpdesk-ingress
  namespace: helpdesk-app
  annotations:
    # Bu anotasyon, NGINX Ingress Controller'ı kullandığınızı belirtir.
    kubernetes.io/ingress.class: "nginx"
    # GEREKSİZ anotasyonlar kaldırıldı. Regex veya rewrite'a bu senaryoda ihtiyaç yok.
spec:
  rules:
  - host: helpdesk.cloudpro.com.tr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Frontend servisi doğru şekilde hedefleniyor.
            name: frontend
            port:
              # Frontend servisinin portu 80.
              number: 80
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              # auth-service'in Service portu 80.
              number: 80
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              # user-service'in Service portu 80.
              number: 80
      - path: /api/tickets
        pathType: Prefix
        backend:
          service:
            name: ticket-service
            port:
              # ticket-service'in Service portu 80.
              number: 80