# ingress/helpdesk-ingress.yaml (TLS Aktifleştirilmiş Son Hali)

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpdesk-ingress
  namespace: helpdesk-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - helpdesk.cloudpro.com.tr
    secretName: helpdesk-tls-secret
  rules:
  - host: helpdesk.cloudpro.com.tr
    http:
      paths:
      - path: /api/auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 80

      # User Service: /api/users/* isteklerini / * olarak user-service'e yönlendirir.
      - path: /api/users(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 80

      # Ticket Service: /api/tickets/* isteklerini / * olarak ticket-service'e yönlendirir.
      - path: /api/tickets(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ticket-service
            port:
              number: 80
      
      # Frontend: Bu kuralın bir rewrite'a ihtiyacı YOKTUR.
      # Ancak yukarıdaki global rewrite-target'tan etkilenmemesi için
      # bu şekilde özel bir Ingress tanımı daha temiz olabilir.
      # Şimdilik bu yapı çalışacaktır. Önce API'ları düzeltelim.
      # NOT: Frontend için ayrı bir Ingress oluşturmak daha temiz bir yöntemdir,
      # ama şimdilik bu şekilde devam edelim.
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 80