# user-service-chart/templates/deployment.yaml (Güvenlik Konteksti Eklenmiş Nihai Hali)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      # --- YENİ EKLENEN POD GÜVENLİK AYARLARI ---
      securityContext:
        runAsNonRoot: true # Pod'un root olarak çalışmasını engeller
        runAsUser: 1001     # Konteynerin çalışacağı kullanıcı ID'si (Bitnami imajları için 1001 yaygındır)
        fsGroup: 1001       # Dosya sistemine erişim için grup ID'si
        seccompProfile:
          type: RuntimeDefault # Güvenli seccomp profili
      containers:
        - name: user-service
          # --- YENİ EKLENEN KONTEYNER GÜVENLİK AYARLARI ---
          securityContext:
            allowPrivilegeEscalation: false # Yetki yükseltmeyi engeller
            capabilities:
              drop:
                - "ALL" # Tüm Linux yeteneklerini kaldırır
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: {{ .Values.config.databaseUrl }}
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3