replicaCount: 1

image:
  repository: harbor.cloudpro.com.tr/helpdesk/placeholder
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

# Gelecekte Ingress veya environment variables gibi eklemeler için yer
ingress:
  enabled: false
env: {}